[features]
seeds = false
skip-lint = false
[programs.localnet]
nft_lend_borrow = "AR7FastXfwZX2q1KsEhWwdFZJqhzr8dFqUvwBhAs1s77"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/user/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
